# Site settings
title: Stone Path Engineering
email: bailey@stonepathengineering.com
url: https://github.com/Stone-Path-Engineering/
description: "Now part of Spark Embedded, LLC"
keywords: "embedded development, firmware, engineering"
skills: "Consulting and Training"
meta_author: Steinfadt Bailey

# Google webmaster tools
#google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:        # #31E042
  primary: 32cfe0 #80B3FF
  primary-rgb: "50,207,224" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Stone Path Engineering
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/stonepatheng
  - title: github
    url: https://github.com/Stone-Path-Engineering/
  - title: linkedin
    url: https://www.linkedin.com/company/stone-path/

# Postal address (add as many lines as necessary)
address:
  - line: West Des Moines

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  - what_i_do
  - experiences
